### ISSUE TITLE
Input required and not supplied: commit

### ISSUE THREAD

**Issue by kirqe** [gavv/pull-request-artifacts#119]
What could be the problem of `Input required and not supplied: commit`
at ` commit: ${{ github.event.pull_request.head.sha }}`
Taken from the README

```
      - name: Pull request artifacts
        uses: gavv/pull-request-artifacts@v1.0.0
        with:
          commit: ${{ github.event.pull_request.head.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: ...
```

After searching, I noticed that people use `if: ${{ github.event_name == 'pull_request_target' || github.event_name == 'pull_request' }}`

It's not clear how to make this action to post comments to the current pull request
