### ISSUE TITLE
Upload Failure - 403 Error returned

### ISSUE THREAD

**Issue by eriknyk** [gavv/pull-request-artifacts#91]
Upload failed in step:
  
 Output.
```
Run gavv/pull-request-artifacts@v1.0.0
Artifacts repo: eriknyk/my-demo-repo
Artifacts branch: artifacts
(node:2273) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
GET /repos/eriknyk/towbook-android-experimental/contents/?ref=artifacts - 404 in 223ms
Uploading file pr1-towbook-2.9.37-30365.apk (first time)
PUT /repos/eriknyk/my-demo-repo/contents/pr1-my-demo-repo-2.9.37-30365.apk - 403 in [19](https://github.com/eriknyk/my-demo-repo/actions/runs/4178992925/jobs/7238431735#step:9:19)92ms

Error: Resource not accessible by integration
```

I have my action configured as following:

```
name: "Android apk build from Pull Request #"
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
jobs:
  build:
    name: build-publish-job
    runs-on: ubuntu-latest
    steps:
     - name: Pull request artifacts
        if: ${{ github.event_name == 'pull_request' }}
        uses: gavv/pull-request-artifacts@v1.0.0
        with:
          commit: ${{ github.event.pull_request.head.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          artifacts-branch: artifacts
          artifacts: |
            ${{ env.OUTPUT_PATH }}/apk/release/2.9.37-30365.apk
```
